### ISSUE TITLE
Historical Leaderboard Setup

### ISSUE THREAD

**Issue by brian-nguyen** [ubclaunchpad/bumper#182]
Investigate persistent storage options for a historical leaderboard.

We should also consider DBaaS

**Comment by brian-nguyen** [comment]
Not blocked anymore. Firebase config is all in a JSON file, so does not require any environment variables. 

We will transfer this config to the VPS.

**Comment by Grafne23** [comment]
The config is only good like that if we keep the DB handling entirely done by the server. I think we should have the clients query the DB directly once they've died - for that I think we'll need an API key.

Also todo - the way I'm sending the db data right now causes a bit of a hang, will look at doing it asynchronously.

**Comment by brian-nguyen** [comment]
Yes, they will have the API key. The idea behind my comment is to have the config(s) available at build time so that it can be included in the production build of the client rather than hardcoding/importing/parsing it.

**Comment by brian-nguyen** [comment]
Administrative
- [ ] Firebase SDK added to server (includes service account)
- [ ] Firebase library added to client
- [ ] Schema for leaderboard data
- [ ] Access rules for data

Implementation (Client)
- [ ] Subscribe to leaderboard data on client (printing is fine)

Implementation (Server)
- [ ] Package for DB functions
- [ ] Tests for DB functions
- [ ] Make calls non-blocking

**Comment by Grafne23** [comment]
Questions for you:
- Firebase SDK added to server (includes service account) -> Can you just ftp that .json file over for me?
- Access rules for data -> currently only the server can write, I think anyone can read though - for the production db we can limit that to just requests from the bumper url. I think that's good enough yeah?

Still to do:
- Dev/Prod databases -> I haven't done this yet. I'll setup another firebase project and have to figure out how to do the go side, similar to how you did the environment variables on the client.
- Make calls non-blocking -> By calling set score as a go routine it makes it async, I'm a little worried this could lead to a concurrency bug if it's called for the same player in close enough succession - I'm still looking into that

**Comment by brian-nguyen** [comment]
> Firebase SDK added to server (includes service account) -> Can you just ftp that .json file over for me?

I think you've already done this. The `Bumper-DB....json` is the service account.

> Access rules for data -> currently only the server can write, I think anyone can read though - for the production db we can limit that to just requests from the bumper url. I think that's good enough yeah?

I think that's good enough :)

> Dev/Prod databases -> I haven't done this yet. I'll setup another firebase project and have to figure out how to do the go side, similar to how you did the environment variables on the client.

Hmm, I think we can make that a separate task for someone else. The work you have rn is already good enough for a merge.

>  Make calls non-blocking -> By calling set score as a go routine it makes it async, I'm a little worried this could lead to a concurrency bug if it's called for the same player in close enough succession - I'm still looking into that

See my review
